//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGetCotacao.ConexaoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotacao
    {
        public int CotacaoID { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime DataInclusao { get; set; }
    }
}
